= Tree Surgeon
:toc:

Tree surgeon is a tool for filtering file trees. Filtering expressions are defined via a mini-language, and can then be applied to directories.

Tree surgeon is primarily intended to be an intermediary tool, called by other applications rather than by the user directly. However, there are a few user-centric use cases, particulary when inter-operating with a shell:

* Show a `tree`-style diff to illustrate what happens when applying a filter to a directory:
[source,haskell]
tree-surgeon show-diff -f 'nameEndsWith ".c"' -s ./my-project

* Recursively remove all `*.tmp` files in sub-directories named `.cache` from a directory:
[source,haskell]
tree-surgeon to-bash -f 'nameEndsWith ".tmp" & ancestorNameIs ".cache"' -s ./my-project | xargs rm

* Find and replace the string "Apple" with "Orange" in all ".cpp" or ".hpp" files:
[source,haskell]
tree-surgeon to-bash -f 'nameEndsWith [".cpp", ".hpp"]' -s ./my-project | xargs sed -i 's/Apple/Orange/g'

- copy a directory filtered
- show comparative
- create .gitignore (probably doesn't need to be special)

== Take the xref:language_tour.adoc#[language tour]
