= Language tour

== Tree surgeon expressions can be thought of as functions
Tree surgeon uses a mini-language to define its filters, that can then be applied to directory trees. A filter expression can be thought of as a function that takes a single argument - the file that is being examined for inclusion/exclusion - and returns a boolean value, where True indicates that the file should be included.

xref:faq.adoc#why-not-directories[Why does tree-surgeon not filter on directories as well as files?]

These expressions are composed of _matcher functions_ and logical operators.

An example of a very simple expression is:
[source,haskell]
nameIs "includeMe.txt"

Which tells tree surgeon to include any file named `includeMe.txt`. Tree surgeon will traverse the whole of the directory tree you specify, and for all files, test whether they match this expression. So in this case, any file named `includeMe.txt`, at any depth of the directory tree, will be included.

== Sub-expressions can be linked with & and |
This main expression can be composed of sub-expressions, linked via `&` (and) and `|` (or) operators. For example:
[source,haskell]
nameIs "this" | nameIs "that"

Will include any files (at any depth of the tree) that have a filename of "this", *or* any files that have the filename of "that".
[sidebar]
As shown shortly, this can also be expressed as `nameIs ["this", "that"]`.

Conversely,
[source,haskell]
nameStartsWith "src" & nameEndsWith "cpp"

Will include only files (at any depth) that have a filename that _starts_with "src", and ends with "cpp"; this includes
* `srcFile.cpp`
* `a/b/c/srcMain.cpp`
but *not*
* `Main.cpp`
* `srcFile`

== Expressions can be parenthesized and negated
Expressions can be put into parentheses, so
[source,haskell]
( nameIs "Main.cpp" | ancestorNameIs "src" )

is the same as

[source,haskell]
nameIs "Main.cpp" | ancestorNameIs "src"

They can also be negated by the `!` operator, so:
[source,haskell]
!(nameStartsWith "Main")

Will include all files _except_ those that start with "Main".

== Matcher functions can take either a single argument, or a list of arguments
All matcher functions can be passed either a single argument, or a list of arguments. Passing a list is equivalent to using the same matcher function multiple times on each argument in the list, and combining the results with the *or* operator, `|`. So

[source,haskell]
nameIs ["Main.cpp", "Lib.cpp", "Lib.hpp"]

is the same as

[source,haskell]
nameIs "Main.cpp" | nameIs "Lib.cpp" | nameIs "Lib.hpp"

xref:matchers.adoc[A complete list of matcher functions]

